export const RECEIVED_EXPENSES = 'RECEIVED_EXPENSES';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';

export const RECEIVED_EXCHANGE_RATE_RESPONSE =
  'RECEIVED_EXCHANGE_RATE_RESPONSE';
